services:
  auth:
    build: ./auth
    command: bash -c 'while !</dev/tcp/message_broker/9092; do sleep 1; done; uvicorn main:app --host 0.0.0.0 --reload'
    volumes:
      - ./auth:/app
    ports:
      - 8001:8000
    environment:
      - AUTH_DB_URL=postgresql+asyncpg://postgres:${AUTH_DB_PASSWORD}@auth_db:5432/postgres
      - AUTH_ROOT_PASSWORD=${AUTH_ROOT_PASSWORD:?}
      # - AUTH_SECRET_KEY=${AUTH_SECRET_KEY:?}
      - KAFKA_URL=message_broker:9092
    depends_on:
      - auth_db
      - message_broker

  auth_db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_PASSWORD=${AUTH_DB_PASSWORD:?}

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  message_broker:
    image: confluentinc/cp-kafka:7.5.0
    hostname: message_broker
    container_name: message_broker
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
      - "9092:9092"
      - "9101:9101"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://message_broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost

volumes:
  postgres_data:
